Repository 42LTeam/pong, pull requests merged in 2023-08, with the labels that each got.

#37 Patching localhost hardcode
  back/src/auth/auth.controller.ts
  back/src/main.ts
  front/src/api.ts
  front/src/containers/Auth.tsx
Labels: bad practices

#45 43 front right click on some elements
  back/src/channel/channel.service.ts
  back/src/user/user.service.ts
  front/src/api.ts
  front/src/components/friend/Friend.tsx
  front/src/components/utils/Button.tsx
  front/src/components/utils/ContextMenu.tsx
  front/src/components/utils/PopUp.tsx
  front/src/containers/social/friend/FriendList.tsx
  front/src/css/notification.css
Labels: enhancement

#74 54 front channel member popup
  .gitignore
  back/package-lock.json
  back/package.json
  back/src/channel/channel.service.ts
  back/src/channel/controllers/channel.controller.ts
  back/src/client/client.gateway.ts
  front/.prettierrc.json
  front/package-lock.json
  front/package.json
  front/src/api.ts
  front/src/components/channelpanel/ChannelMember.tsx
  front/src/components/conversation/Conversation.tsx
  front/src/components/utils/SidePanel.tsx
  front/src/containers/social/SocialBody.tsx
  front/src/containers/social/channel/ChannelMembersList.tsx
  front/src/containers/social/chat/Chat.tsx
  front/src/containers/social/conversation/Conversations.tsx
  front/src/main.tsx
Labels: enhancement, New feature

#97 Fix paths
  back/src/client/gateways/game.gateway.ts
Labels: bug
